version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: saturday
      time: "09:00"
    groups:
      github_action-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "15:00"

  - package-ecosystem: gitsubmodule
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
