name: Docker Image CI (Test Build)

on:
  pull_request:
    branches: [ "main", "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ubuntu-xrdp:$(date +%s)
